trigger: none

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Test the project'
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**.bicep'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Bicep'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: DeployAzureResources
  displayName: Deploy Azure Resources 
  jobs:
  - job: DeployBicepTemplate
    displayName: Deploy Bicep Template
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(ResourceGroupName) --location $(location)
           az deployment group create `
           --name $(Build.BuildNumber) `
           --resource-group $(ResourceGroupName) `
           --template-file $(System.ArtifactsDirectory)/Bicep/TailspinResources.bicep `
           --parameters websiteName=$(WebsiteName) hostingPlanName=$(HostingPlan)
    
-  stage: DeployToDevAndStaging
   displayName: Deploy to Dev and Staging Environments
   jobs:
   - deployment: DeployToDev
     displayName: Deploy To Dev Environment
     pool:
       vmImage: 'windows-latest'
     environment: 'Dev'
     strategy:
      runOnce:
          deploy:
              steps:   
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
                  appType: 'webApp'
                  WebAppName: '$(WebsiteName)'
                  deployToSlotOrASE: true
                  ResourceGroupName: '$(ResourceGroupName)'
                  SlotName: 'Dev'
                  packageForLinux: '$(Pipeline.Workspace)/**/*Web.zip'
   
   - deployment: DeployToStaging
     displayName: Deploy To Staging Environment
     pool:
       vmImage: 'windows-latest'
     environment: 'Staging'
     strategy:
      runOnce:
          deploy:
              steps:   
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
                  appType: 'webApp'
                  WebAppName: '$(WebsiteName)'
                  deployToSlotOrASE: true
                  ResourceGroupName: '$(ResourceGroupName)'
                  SlotName: 'Staging'
                  packageForLinux: '$(Pipeline.Workspace)/**/*Web.zip'

- stage: DeployToProd
  displayName: Deploy to Production
  jobs:
  - deployment: DeployToProd
    displayName: Deploy To Production Environment
    pool:
      vmImage: 'windows-latest'
    environment: 'Production'
    strategy:
      runOnce:
          deploy:
              steps:   
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
                  appType: 'webApp'
                  WebAppName: '$(WebsiteName)'
                  deployToSlotOrASE: true
                  ResourceGroupName: '$(ResourceGroupName)'
                  SlotName: 'Production'
                  packageForLinux: '$(Pipeline.Workspace)/**/*Web.zip'
