# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - 'main'
  paths:
    exclude:
      - README.md

name: $(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd).$(rev:rr)

parameters:
- name: workloadName
  displayName: Target Workload Name
  type: string
  default: 'workload-prod-fa'

stages:
- stage: build
  jobs:
  - template: .pipeline/job_templates/build.yml
    parameters:
      preBuildSteps: []
      buildConfiguration: 'release'

- template: .pipeline/stage_templates/deployWorkload.yml
  parameters:
    workloadName: 'targetworkload-prod-fa'

- stage: configure
  dependsOn: deploy
  jobs:
  - job: deploy_staging
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "configure"