trigger: none

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Test the project'
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**.bicep'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Bicep'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(ResourceGroupName) --location $(location)
           az deployment group create `
           --name $(Build.BuildNumber) `
           --resource-group $(ResourceGroupName) `
           --template-file $(System.ArtifactsDirectory)/Bicep/TailspinResources.bicep `
           --parameters websiteName=$(WebsiteName) hostingPlanName=$(HostingPlan)
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MCAPS-Hybrid-REQ-53192-2023-damienaicheh(90fdcd92-f0b2-4dde-89c8-c5ab5c06e7ec)'
        appType: 'webApp'
        WebAppName: '$(WebsiteName)'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*Web.zip'